---
- hosts: leafs_DC1
  gather_facts: no
  tasks:

  - name: Add ACL
    eos_config:
      lines:
      - 10 permit ip host 192.0.2.1 any log
      - 20 permit ip host 192.0.2.2 any log
      - 30 permit ip host 192.0.2.3 any log
      - 40 permit ip host 192.0.2.4 any log
      diff_against: 'running'
      parents: ip access-list test
      before: no ip access-list test
      replace: block
    register: response1
    ignore_errors: True

  - name: Print response1
    debug:
      var: response1.diff.after.splitlines()